name: Docker Image

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
      - ".github/workflows/auto-update.yml"
  pull_request:

jobs:
  docker-image-alpine:
    strategy:
      matrix:
        # MUST ORDER versions ascending
        rewinged:
          - version: "0.3.0"
            version_major: ""
            version_minor: ""
            download_hash: "994ee46335c8de233cbaeba51d16593b3eb15b3d14b5b1c6c282dd78d3e43e9f"
            latest: false
          - version: "0.4.0"
            version_major: ""
            version_minor: ""
            download_hash: "9e529e575b80813d2b46759e789ab311dae9749ed860d78bf56021e722e8539e"
            latest: false
          - version: "0.5.0"
            version_major: ""
            version_minor: ""
            download_hash: "33cc58f70a573f11a4e24eaf475c91d30b5515ddf065aa5aa0f0061f0cc2ebc2"
            latest: false
          - version: "0.6.0"
            version_major: ""
            version_minor: ""
            download_hash: "7b0bf0cd99b6bb5c646c5d8b98b42af62b3e92a2f5e9ef5ca6d28e66a314e600"
            latest: false
          - version: "0.6.1"
            version_major: ""
            version_minor: ""
            download_hash: "c3d22d5407ae556ccc0d6653235239fcb2c263919a97a7ebde20705528a880fa"
            latest: false
          - version: "0.7.1"
            version_major: ""
            version_minor: ""
            download_hash: "dcf0158dbb71612491dc7f9f0260ee1b6e372f3b94f14735ef626343e7f79111"
            latest: true

    env:
      IMAGE_NAME_FULL: "fabiang/rewinged:${{ matrix.rewinged.version }}-alpine"
      IMAGE_NAME_MINOR: "fabiang/rewinged:${{ matrix.rewinged.version_minor }}-alpine"
      IMAGE_NAME_MAJOR: "fabiang/rewinged:${{ matrix.rewinged.version_major }}-alpine"
      DOCKER_BUILDKIT: 1

    runs-on: ubuntu-latest
    permissions:
      actions: write

    name: "Alpine v${{ matrix.rewinged.version }}"

    steps:
      - uses: actions/checkout@v3

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true

      - name: Build Image
        run: |
          docker build -f alpine/Dockerfile \
            -t '${{ env.IMAGE_NAME_FULL }}' \
            \
            --build-arg 'REWINGED_VERSION=${{ matrix.rewinged.version }}' \
            --build-arg 'REWINGED_DOWNLOAD_HASH=${{ matrix.rewinged.download_hash }}' \
            .

      - name: Test Image
        run : |
          docker run -i --rm ${{ env.IMAGE_NAME_FULL }} --version

      - name: Tag Minor
        if: "${{ matrix.rewinged.version_minor != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.rewinged.version_major != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'

      - name: Docker Hub login
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'

      - name: Push Image Minor
        if: "${{ matrix.rewinged.version_minor != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'

      - name: Push Image Major
        if: "${{ matrix.rewinged.version_major != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'

  docker-image-windows:
    strategy:
      matrix:
        windows:
          - image: servercore
            version: ltsc2019
            build_version: 1809
            runs_on: 2019
          - image: servercore
            version: ltsc2022
            build_version: ltsc2022
            runs_on: 2022
        rewinged:
          # MUST ORDER versions ascending
          - version: "0.3.0"
            version_major: ""
            version_minor: ""
            download_hash: "deb6df1749dec36f26bb4edd4387dfb17e40358663cca903d703230bf15bddf5"
            latest: false
          - version: "0.4.0"
            version_major: ""
            version_minor: ""
            download_hash: "49fbcc09e47e922dcf92a997a391359b0209c95bb037c237f0c209d6bb4c7e81"
            latest: false
          - version: "0.5.0"
            version_major: ""
            version_minor: ""
            download_hash: "dc7618aaedd731971bd876142b7dd301dc0d8a0305677c07b2041ab3d0d5d070"
            latest: false
          - version: "0.6.0"
            version_major: ""
            version_minor: ""
            download_hash: "6db9dbaff5de9349edca9f2fbb4c3bc9fa5c165544a5f8f79e1b946b55206703"
            latest: false
          - version: "0.6.1"
            version_major: ""
            version_minor: ""
            download_hash: "63a08fdc9c28e75344832644deeacd10a4f34fe1c8e92ee0237bfa49e9659117"
            latest: false
          - version: "0.7.1"
            version_major: ""
            version_minor: ""
            download_hash: "6ca17952381fb5f7fb0bb73af17b5f290d576461a7bc05de19c9665d2274c162"
            latest: true

    env:
      IMAGE_NAME_FULL: "fabiang/rewinged:${{ matrix.rewinged.version }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"
      IMAGE_NAME_MINOR: "fabiang/rewinged:${{ matrix.rewinged.version_minor }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"
      IMAGE_NAME_MAJOR: "fabiang/rewinged:${{ matrix.rewinged.version_major }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"

    runs-on: windows-${{ matrix.windows.runs_on }}
    permissions:
      actions: write

    name: "Win v${{ matrix.rewinged.version }} (${{ matrix.windows.image }} – (${{ matrix.windows.version }})"

    steps:
      - uses: actions/checkout@v3

      # Githubs Cache with 10GB is to small
      #      - uses: jpribyl/action-docker-layer-caching@v0.1.1
      #        continue-on-error: true

      - name: Build Image
        run: |
          docker build -f windows/Dockerfile `
            -t '${{ env.IMAGE_NAME_FULL }}' `
            `
            --build-arg 'REWINGED_VERSION=${{ matrix.rewinged.version }}' `
            --build-arg 'REWINGED_DOWNLOAD_HASH=${{ matrix.rewinged.download_hash }}' `
            `
            --build-arg 'WINDOWS_IMAGE=${{ matrix.windows.image }}' `
            --build-arg 'WINDOWS_VERSION=${{ matrix.windows.version }}' `
            --build-arg 'WINDOWS_VERSION_BUILD=${{ matrix.windows.build_version }}' `
            .

      - name: Tag Minor
        if: "${{ matrix.rewinged.version_minor != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.rewinged.version_major != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'

      - name: Test image
        run: |
          docker run -t --rm --entrypoint='' `
            '${{ env.IMAGE_NAME_FULL }}' `
            rewinged -version

      - name: Docker Hub login
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'

      - name: Push Image Minor
        if: "${{ matrix.rewinged.version_minor != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'

      - name: Push Image Major
        if: "${{ matrix.rewinged.version_major != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'
