name: Docker Image

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
  pull_request:
  schedule:
    - cron: "0 12 1-7 * 2"

jobs:
  docker-image-alpine:
    strategy:
      matrix:
        rewinged:
          # lts: true should also be the latest version of the LTS versions (so only one lts: true)
          - version: "0.5.0"
            version_minor: ""
            version_major: ""
            download_hash: "33cc58f70a573f11a4e24eaf475c91d30b5515ddf065aa5aa0f0061f0cc2ebc2"
          - version: "0.4.0"
            version_minor: ""
            version_major: ""
            download_hash: "9e529e575b80813d2b46759e789ab311dae9749ed860d78bf56021e722e8539e"
          - version: "0.3.0"
            version_minor: ""
            version_major: ""
            download_hash: "994ee46335c8de233cbaeba51d16593b3eb15b3d14b5b1c6c282dd78d3e43e9f"

    env:
      IMAGE_NAME_FULL: "fabiang/rewinged:${{ matrix.rewinged.version }}-alpine"
      IMAGE_NAME_MINOR: "fabiang/rewinged:${{ matrix.rewinged.version_minor }}-alpine"
      IMAGE_NAME_MAJOR: "fabiang/rewinged:${{ matrix.rewinged.version_major }}-alpine"
      DOCKER_BUILDKIT: 1

    runs-on: ubuntu-latest

    name: "Alpine v${{ matrix.rewinged.version }}"

    steps:
      - uses: actions/checkout@v3

      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true

      - name: Build Image
        run: |
          docker build -f alpine/Dockerfile \
            -t '${{ env.IMAGE_NAME_FULL }}' \
            \
            --build-arg 'REWINGED_VERSION=${{ matrix.rewinged.version }}' \
            --build-arg 'REWINGED_DOWNLOAD_HASH=${{ matrix.rewinged.download_hash }}' \
            .

      - name: Test Image
        run : |
          docker run -i --rm ${{ env.IMAGE_NAME_FULL }} --version

      - name: Tag Minor
        if: "${{ matrix.rewinged.version_minor != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.rewinged.version_major != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'

      - name: Docker Hub login
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'

      - name: Push Image Minor
        if: "${{ matrix.rewinged.version_minor != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'

      - name: Push Image Major
        if: "${{ matrix.rewinged.version_major != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'

  docker-image-windows:
    strategy:
      matrix:
        windows:
          - image: servercore
            version: ltsc2019
            build_version: 1809
            runs_on: 2019
          - image: servercore
            version: ltsc2022
            build_version: ltsc2022
            runs_on: 2022
        rewinged:
          - version: "0.5.0"
            version_minor: ""
            version_major: ""
            download_hash: "dc7618aaedd731971bd876142b7dd301dc0d8a0305677c07b2041ab3d0d5d070"
          - version: "0.4.0"
            version_minor: ""
            version_major: ""
            download_hash: "49fbcc09e47e922dcf92a997a391359b0209c95bb037c237f0c209d6bb4c7e81"
          - version: "0.3.0"
            version_minor: ""
            version_major: ""
            download_hash: "deb6df1749dec36f26bb4edd4387dfb17e40358663cca903d703230bf15bddf5"

    env:
      IMAGE_NAME_FULL: "fabiang/rewinged:${{ matrix.rewinged.version }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"
      IMAGE_NAME_MINOR: "fabiang/rewinged:${{ matrix.rewinged.version_minor }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"
      IMAGE_NAME_MAJOR: "fabiang/rewinged:${{ matrix.rewinged.version_major }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"

    runs-on: windows-${{ matrix.windows.runs_on }}

    name: "Win v${{ matrix.rewinged.version }} (${{ matrix.windows.image }} – (${{ matrix.windows.version }})"

    steps:
      - uses: actions/checkout@v3

      # Githubs Cache with 10GB is to small
      #      - uses: jpribyl/action-docker-layer-caching@v0.1.1
      #        continue-on-error: true

      - name: Build Image
        run: |
          docker build -f windows/Dockerfile `
            -t '${{ env.IMAGE_NAME_FULL }}' `
            `
            --build-arg 'REWINGED_VERSION=${{ matrix.rewinged.version }}' `
            --build-arg 'REWINGED_DOWNLOAD_HASH=${{ matrix.rewinged.download_hash }}' `
            `
            --build-arg 'WINDOWS_IMAGE=${{ matrix.windows.image }}' `
            --build-arg 'WINDOWS_VERSION=${{ matrix.windows.version }}' `
            --build-arg 'WINDOWS_VERSION_BUILD=${{ matrix.windows.build_version }}' `
            .

      - name: Tag Minor
        if: "${{ matrix.rewinged.version_minor != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.rewinged.version_major != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'

      - name: Test image
        run: |
          docker run -t --rm --entrypoint='' `
            '${{ env.IMAGE_NAME_FULL }}' `
            rewinged -version

      - name: Docker Hub login
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'

      - name: Push Image Minor
        if: "${{ matrix.rewinged.version_minor != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'

      - name: Push Image Major
        if: "${{ matrix.rewinged.version_major != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'
